version: "3.9"

services:
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  petclinic-crac:
    build: .
    image: petclinic-crac
    container_name: petclinic-crac
    ports:
      - "8080:8080"
    volumes:
      - ./checkpoints:/checkpoints
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    cap_add:
      - CHECKPOINT_RESTORE
    security_opt:
      - seccomp=unconfined
    depends_on:
      - mysql
